FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /src
RUN apt-get update && apt-get -qq -y install python3
COPY SS14.Changelog/*.csproj .
RUN dotnet restore
COPY SS14.Changelog .
RUN dotnet publish -c Release --no-self-contained -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
RUN apt-get -y update
RUN apt-get -y install git
RUN mkdir repo

ENTRYPOINT ["./SS14.Changelog"]
