FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /src
COPY SS14.Watchdog/*.csproj .
RUN dotnet restore
COPY SS14.Watchdog .
RUN dotnet publish -c Release --no-self-contained -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
COPY --from=mcr.microsoft.com/dotnet/aspnet:7.0 /usr/share/dotnet/shared /usr/share/dotnet/shared
WORKDIR /publish
COPY --from=build-env /publish .
RUN mkdir data
EXPOSE 80
ENTRYPOINT ["./SS14.Watchdog"]
