FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /src
COPY SS14 SS14/
COPY SS14.Admin SS14.Admin/
RUN dotnet restore ./SS14.Admin
RUN dotnet publish -c Release --no-self-contained -o /publish ./SS14.Admin

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
EXPOSE 27690
ENTRYPOINT ["./SS14.Admin"]
