FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /src
COPY SS14.Changelog/*.csproj .
RUN dotnet restore
COPY SS14.Changelog .
RUN dotnet publish -c Release --no-self-contained -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
RUN mkdir repo

ENTRYPOINT ["./SS14.Changelog"]
